Month 7/step 2
Danbka-Taranbka/react-burger pull request #3
Opened 2023-05-06 18:07 UTC by Danbka-Taranbka

Проведена работа над модальными окнами. Добавлена функция отображения дополнительной информации об ингредиентах, отображения информации о заказе.

2023-05-07 16:41 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Есть модальные окна;
- Данные получают с сервера;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/OTlb7YkpBK8vYg> - Нужно убрать модальное окно по нажатию на ингредиенты конструктора, т.к. в будущем пользователь будет передвигать их с помощью DnD;

- Отметил замечания в коде;

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-05-07 16:41 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.js
> +  }
**Можно лучше:**

лучше создать отдельный компоненте, а не функцию, и через пропс прокидывать ингредиент

2023-05-07 16:41 UTC, ArslanMustafin commented on src/api/api.js
> +export default class Api extends React.Component {
**Надо исправить:**

класс не должен наследоваться от `React.Component`, это не компонент. Соответсвенно `super(props);` и параметр `props` нужно убрать.

И лучше написать вот так.

```js
class Api {...}
export default new Api();
```

2023-05-07 16:41 UTC, ArslanMustafin commented on src/api/api.js
> +    this.ingredients = "ingredients";
**Надо исправить:**

В будущем будет ещё много запросов, поэтому адрес лучше напрямую в запросе писать, а не выносить в отдельные переменные

2023-05-07 16:41 UTC, ArslanMustafin commented on src/components/app/app.js
> +    .then(( {data} ) => setState({...state, data, isLoading: false }))
**Можно лучше:**

тут лучше использовать функциональное обновление `useState`, из-за асинхронности.

https://react.dev/reference/react/useState#updating-state-based-on-the-previous-state

2023-05-07 16:41 UTC, ArslanMustafin commented on src/components/app/app.js
> +  const [kind, setKind] = useState(null);
**Надо исправить:**

Вы должны для каждого контента писать своё модальное окно и свои обработчики открытия/закрытия.

```js
{isOpenIngredientModal && <Modal onClose={handleCloseIngredientModal}><IngredientDetails /></Modal>}
{isOpenOrderModal && <Modal onClose={handleCloseOrderModal}><OrderDetails /></Modal>}
```

2023-05-07 16:41 UTC, ArslanMustafin commented on src/components/app/app.js
> +    {state.data.length && <BurgerConstructor data={state.data} openIngredient={openIngredient} confirmOrder={openOrderDetails}/>}
**Можно лучше:**

лучше объядинить: 

```js
!!state.data.length && <>...</>
```

2023-05-07 16:41 UTC, ArslanMustafin commented on src/components/modal/modal.js
> +    document.addEventListener("mousedown", handleOverlayClose);
**Надо исправить:**

Вы можете вешать событие `onClicl` на элемент. Не нужно делать такое с документом.

Лучше реализуйте следующую структуру: 

```js
<>
 <ModalOverlay onClose={onClose} />
 <div className={styles.modal}>...</div>
<>
```

2023-05-07 16:41 UTC, ArslanMustafin commented on src/components/modal/modal.js
> +};
**Надо исправить:**

Описаны не все пропсы: `children`

2023-05-07 16:41 UTC, ArslanMustafin commented on src/components/modal-overlay/modal-overlay.js
> +export default function ModalOverlay ({children}) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-05-07 16:41 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.js
> +        <Button htmlType="button" type="primary" size="small" extraClass="p-10 pt-5 pb-5 ml-10 text text_type_main-small" onClick={() => {confirmOrder()}}>
**Можно лучше:**

```js
onClick={confirmOrder}
```

Лучше написать вот так, иначе у вас каждый раз будет создаваться новая функция, и будет происходить перерендер.

2023-05-08 18:39 UTC, Danbka-Taranbka commented on src/components/app/app.js
> +    .then(( {data} ) => setState({...state, data, isLoading: false }))
Не очень понял, о чём идёт речь. Необходимо обернуть в функцию? :
 `.then(() => {( {data} ) => setState({...state, data, isLoading: false })})`

2023-05-08 20:00 UTC, Danbka-Taranbka commented on src/components/modal/modal.js
> +    document.addEventListener("mousedown", handleOverlayClose);
Теперь закрывается на и на клик по самому модальному окну, не понимаю, как это исправить(

2023-05-08 20:03 UTC, closed without merging

2023-05-09 10:50 UTC, ArslanMustafin commented on src/components/app/app.js
> +    .then(( {data} ) => setState({...state, data, isLoading: false }))
```js
.then(( {data} ) => setState((prevState) => ({...prevState, data, isLoading: false }) ))
```

2023-05-09 10:53 UTC, ArslanMustafin commented on src/components/modal/modal.js
> +    document.addEventListener("mousedown", handleOverlayClose);
Кроме структуры вам нужно ещё чуток подправить стили, чтобы z-index у модального окна был выше, а `modalOverlay`, было за модальным окном. Советую обратиться за помощью к наставнику.