Month 9/step 1
Danbka-Taranbka/react-burger pull request #7
Opened 2023-07-12 20:46 UTC by Danbka-Taranbka

first-itteration

2023-07-12 21:14 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Реализовано обновление токена
- Защита роутов реализована в одном компоненте

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://github.com/remix-run/react-router/blob/dev/examples/modal/src/App.tsx . 

<img width="974" alt="Снимок экрана 2023-07-13 в 00 12 26" src="https://github.com/Danbka-Taranbka/react-burger/assets/60173362/8d5dd2eb-787c-4f75-9997-f82d6545365f">


- Если есть инпуты, то они должны быть внутри тега form, и на этот тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.
- Не авторизованный юзер не должен иметь возможность сделать заказ
- Запрос регистрации возвращает ответом токены и данные юзера, поэтому его можно сразу авторизовать.
- в payload запроса на ресет пароля не попадает код восстановления

<img width="474" alt="Снимок экрана 2023-07-13 в 00 11 11" src="https://github.com/Danbka-Taranbka/react-burger/assets/60173362/a07da8b3-fa1c-458f-a530-0b23934e7233">

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-12 21:14 UTC, andryxxa93 commented on src/components/app/app.js
> +            <Route path="/ingredients/:id" element={<IngredientPage/>}/>
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-07-12 21:14 UTC, andryxxa93 commented on src/pages/reset-password-page.js
> +  const onChange = e => {
**Можно лучше**

Можно сделать универсальный **кастомный** хук для контроля любого количества инпутов в любых формах:
```js
 export function useForm(inputValues) {
   const [values, setValues] = useState(inputValues);
 
   const handleChange = (event) => {
     const {value, name} = event.target;
     setValues({...values, [name]: value});
   };
   return {values, handleChange, setValues};
 }
```
    
Этот код помещают в отдельный файл `useForm.js` в папке `hooks` и импортируют функцию туда, где нужно контролировать инпуты

 И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:
    
 ```js
   const {values, handleChange, setValues} = useForm({});
 ```

2023-07-16 05:12 UTC, andryxxa93 commented
**Необходимо исправить**

 -При открытии деталей ингредиента необходимо, чтобы в адресной строке менял url и подставлялся `id` просматриваемого ингредиента. 
 У вас так -

<img width="853" alt="Снимок экрана 2023-07-16 в 08 07 18" src="https://github.com/Danbka-Taranbka/react-burger/assets/60173362/850a3114-620e-45ff-8713-3196d18552e4">

А должно быть вот так -

<img width="1277" alt="Снимок экрана 2023-07-16 в 08 08 19" src="https://github.com/Danbka-Taranbka/react-burger/assets/60173362/62c6b7ad-6604-4c3c-a952-f25e78c3e974">


Чтобы так работало вам следует подставлять _id ингредиента при переходе. 

Тут лучше использовать компонент Link из `react-router-dom`
```
    <div ref={ref} className={styles.ingredient} id={_id} onClick={() => {
      openIngredient(ingredient);
      navigate("/ingredients/" + ingredient._id)
      }}>
```

2023-07-16 12:32 UTC, Danbka-Taranbka commented
Не очень понял про Link
Имеется в виду представить компонент IngredientItem следующим образом? 

    ```
<Link ref={ref} className={styles.ingredient} id={_id} 
     onClick={() => {openIngredient(ingredient);}}
      to={"/ingredients/" + ingredient._id}
>
      {renderCounter(counter)}
      <img className={styles.image} src={image} alt={name}/>
      <p className={`text text_type_digits-default ${styles.price}`}>{price} <CurrencyIcon/></p>
      <h3 className={`text text_type_main-default ${styles.name}`}>{name}</h3>
    </Link>
```

2023-07-16 18:57 UTC, andryxxa93 commented
**Необходимо исправить**
При открытии по прямой ссылке деталей ингредиента - пустая страница.

<img width="1439" alt="Снимок экрана 2023-07-16 в 21 57 17" src="https://github.com/Danbka-Taranbka/react-burger/assets/60173362/f0b3a153-296b-410b-96ef-07419ebd13ea">

2023-07-16 18:58 UTC, andryxxa93 commented
> Не очень понял про Link Имеется в виду использовать Link вместо div?

Да, вместо div лучше использовать Link

2023-07-16 22:47 UTC, Danbka-Taranbka commented
Проверил, у меня вроде всё работает 
Больше никаких идей(

2023-07-17 08:52 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-09-20 18:10 UTC, merged