Month 9/step 2
Danbka-Taranbka/react-burger pull request #8
Opened 2023-07-20 22:26 UTC by Danbka-Taranbka

2023-07-21 18:15 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;
- Теперь пользователь может посмотреть историю заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/Abh-I1jJMbojOw> - если попытаться открыть заказ в новой вкладке, то возникает ошибка.

- У вас не закрывается сокет соединение, когда пользователь уходит со страницы `/feed` и `/profile/orders`. По чек-листу: Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и закрывается, когда пользователь покидает их. <https://disk.yandex.com/i/-f8yt6g8zYyBjw> - это можно проверить в девтулс, во вкладке `networks`.

- При запуск приложения у вас два раза вызывается запрос `GET /ingredients`, а должен вызываться 1 раз (Оставьте вызов, который в компоненте `app`, а остальные уберите: <https://disk.yandex.com/i/ILdKW1oT09uQqg>). Пользователя тоже лучше запрашивать единожды в компоненте `app`;

- В файлах, где содержится `jsx`, нужно поменять расширение с `.js` на `.jsx`;

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/WXQ6Bwp55cZ-aQ>;

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-07-21 18:15 UTC, ArslanMustafin commented on src/components/order-feed-stats/order-feed-stats.js
> +  }, [orders])
**Можно лучше:**

думаю тут лучше в 1 `useMemo` объединить .

2023-07-21 18:15 UTC, ArslanMustafin commented on src/components/profile-form/profile-form.js
> +  const [form, setFormValue] = useState({email: '', password: '', name: ''});
**Можно лучше:**

Можно сделать универсальный кастомный хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = event => {
    const { value, name } = event.target;
    setValues({ ...values, [name]: value });
  };
  return { values, handleChange, setValues };
}
```

Этот код помещают в отдельный файл useForm.js в папке hooks и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```js
const { values, handleChange, setValues } = useForm({...});
```

2023-07-21 18:15 UTC, ArslanMustafin commented on src/components/order-feed/order-feed.js
> +        .map((order) => {
**Можно лучше:**

Попробуйте сразу использовать метод `toReversed`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toReversed

2023-07-23 17:13 UTC, Danbka-Taranbka commented
К сожалению, я не понимаю, как реализовать отключение ws-соединения
Вроде сделал всё точь-в-точь, как описано в теории, тренажёре, но соединение по-прежнему не закрывается вместе с "размонтированием" компонента

2023-07-24 12:59 UTC, ArslanMustafin commented
> К сожалению, я не понимаю, как реализовать отключение ws-соединения Вроде сделал всё точь-в-точь, как описано в теории, тренажёре, но соединение по-прежнему не закрывается вместе с "размонтированием" компонента

с этим лучше обратиться к наставнику)

2023-07-24 12:59 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но всё ещё есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/RGma1QYAOmPVIA> - Нужно исправить ошибку пр открытии страницы - Лента заказов;

- У вас не закрывается сокет соединение, когда пользователь уходит со страницы `/feed` и `/profile/orders`. По чек-листу: Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и закрывается, когда пользователь покидает их. <https://disk.yandex.com/i/-f8yt6g8zYyBjw> - это можно проверить в девтулс, во вкладке `networks`.

- (я увидел что вы добавили)

  Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали) .

  <https://disk.yandex.com/i/-XVKpYqTmKF-ZA> - Посмотрите на вид токена (как он передаётся) и поправьте его);

2023-07-24 20:24 UTC, Danbka-Taranbka commented
Поправил
Ошибок в ленте не наблюдаю, ws-соединение закрывается при размонтировании компонента, обработка заказа стала долгой)))

2023-07-25 14:23 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

### **Рекомендуется исправить:**

- Страница лента заказов, должна быть доступна всем пользователям.

2023-09-20 18:10 UTC, merged